name: human_canvas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_material_color_picker: ^1.2.0
  image_picker: ^1.0.7
  patterns_canvas: ^0.5.0
  path_drawing: ^1.0.1
  xml: ^6.3.0
  flutter_svg: ^2.0.10+1
  file_picker: ^8.1.4
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
